// Generated by MSTest Unit Test Writer Skill
using InterpolationApi.Controllers;
using InterpolationApi.Controllers.Dtos;
using InterpolationApi.Operations.GeneratePresignedUrls;
using InterpolationApi.Operations.SubmitJob;
using Microsoft.AspNetCore.Mvc;
using Moq;

namespace InterpolationApiTest.Controllers;

[TestClass]
public class JobsControllerTests
{
    private Mock<IGeneratePresignedUrlsOperation> _generatePresignedUrlsOperation = null!;
    private Mock<ISubmitJobOperation> _submitJobOperation = null!;
    private JobsController _sut = null!;

    [TestInitialize]
    public void Setup()
    {
        _generatePresignedUrlsOperation = new Mock<IGeneratePresignedUrlsOperation>();
        _submitJobOperation = new Mock<ISubmitJobOperation>();
        _sut = new JobsController(_generatePresignedUrlsOperation.Object, _submitJobOperation.Object);
    }

    // --- Success path ---

    [TestMethod]
    public async Task PostUpload_WhenOperationSucceeds_ReturnsOkResult()
    {
        var (request, ct) = ValidRequest();
        SetupOperation(ValidResult());

        var actionResult = await _sut.PostUpload(request, ct);

        Assert.IsInstanceOfType<OkObjectResult>(actionResult);
    }

    [TestMethod]
    public async Task PostUpload_WhenOperationSucceeds_MapsRequestToOperationInput()
    {
        var (request, ct) = ValidRequest();
        GeneratePresignedUrlsInput? capturedInput = null;

        _generatePresignedUrlsOperation
            .Setup(o => o.ExecuteAsync(It.IsAny<GeneratePresignedUrlsInput>(), ct))
            .Callback<GeneratePresignedUrlsInput, CancellationToken>((input, _) => capturedInput = input)
            .ReturnsAsync(ValidResult());

        await _sut.PostUpload(request, ct);

        Assert.IsNotNull(capturedInput);
        Assert.AreEqual(request.Email,                capturedInput.Email);
        Assert.AreEqual(request.StartFile.Name,        capturedInput.StartFile.Name);
        Assert.AreEqual(request.StartFile.ContentType, capturedInput.StartFile.ContentType);
        Assert.AreEqual(request.StartFile.Size,        capturedInput.StartFile.Size);
        Assert.AreEqual(request.EndFile.Name,          capturedInput.EndFile.Name);
        Assert.AreEqual(request.EndFile.ContentType,   capturedInput.EndFile.ContentType);
        Assert.AreEqual(request.EndFile.Size,          capturedInput.EndFile.Size);
    }

    [TestMethod]
    public async Task PostUpload_WhenOperationSucceeds_MapsOperationResultToResponse()
    {
        var (request, ct) = ValidRequest();
        var operationResult = ValidResult();
        SetupOperation(operationResult);

        var actionResult = await _sut.PostUpload(request, ct);

        var ok = (OkObjectResult)actionResult;
        var response = (GeneratePresignedUrlsResponse)ok.Value!;
        Assert.AreEqual(operationResult.UploadId,            response.UploadId);
        Assert.AreEqual(operationResult.Start.Key,           response.Start.Key);
        Assert.AreEqual(operationResult.Start.Upload.Url,    response.Start.Upload.Url);
        Assert.AreEqual(operationResult.Start.Upload.Fields, response.Start.Upload.Fields);
        Assert.AreEqual(operationResult.End.Key,             response.End.Key);
        Assert.AreEqual(operationResult.End.Upload.Url,      response.End.Upload.Url);
        Assert.AreEqual(operationResult.End.Upload.Fields,   response.End.Upload.Fields);
    }

    // --- Error path ---

    [TestMethod]
    public async Task PostUpload_WhenOperationThrowsArgumentException_ReturnsBadRequest()
    {
        var (request, ct) = ValidRequest();
        _generatePresignedUrlsOperation
            .Setup(o => o.ExecuteAsync(It.IsAny<GeneratePresignedUrlsInput>(), ct))
            .ThrowsAsync(new ArgumentException("validation failed"));

        var actionResult = await _sut.PostUpload(request, ct);

        Assert.IsInstanceOfType<BadRequestObjectResult>(actionResult);
    }

    [TestMethod]
    public async Task PostUpload_WhenOperationThrowsArgumentException_BadRequestBodyContainsErrorMessage()
    {
        var (request, ct) = ValidRequest();
        var errorMessage = "email is required";
        _generatePresignedUrlsOperation
            .Setup(o => o.ExecuteAsync(It.IsAny<GeneratePresignedUrlsInput>(), ct))
            .ThrowsAsync(new ArgumentException(errorMessage));

        var actionResult = await _sut.PostUpload(request, ct);

        var badRequest = (BadRequestObjectResult)actionResult;
        dynamic body = badRequest.Value!;
        Assert.AreEqual(errorMessage, (string)body.error);
    }

    // --- Helpers ---

    private static (GeneratePresignedUrlsRequest request, CancellationToken ct) ValidRequest() =>
    (
        new GeneratePresignedUrlsRequest
        {
            Email     = "test@example.com",
            StartFile = new FileMetadata { Name = "start.jpg", ContentType = "image/jpeg", Size = 1024 },
            EndFile   = new FileMetadata { Name = "end.png",   ContentType = "image/png",  Size = 2048 }
        },
        CancellationToken.None
    );

    private static GeneratePresignedUrlsResult ValidResult() =>
        new()
        {
            UploadId = "upl_test123",
            Start = new PresignedFrame { Key = "start-key", Upload = new PresignedPost { Url = "https://s3/start", Fields = new() { ["key"] = "start" } } },
            End   = new PresignedFrame { Key = "end-key",   Upload = new PresignedPost { Url = "https://s3/end",   Fields = new() { ["key"] = "end"   } } }
        };

    private void SetupOperation(GeneratePresignedUrlsResult result)
    {
        _generatePresignedUrlsOperation
            .Setup(o => o.ExecuteAsync(It.IsAny<GeneratePresignedUrlsInput>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(result);
    }
}
