// Generated by MSTest Unit Test Writer Skill
using InterpolationApi.Operations.GetStats;
using InterpolationApi.Services;
using Microsoft.Extensions.Logging;
using Moq;

namespace InterpolationApiTest.Operations;

[TestClass]
public class GetStatsOperationTests
{
    private Mock<IDynamoDbService> _dynamoDbService = null!;
    private Mock<ILogger<GetStatsOperation>> _logger = null!;
    private GetStatsOperation _sut = null!;

    [TestInitialize]
    public void Setup()
    {
        _dynamoDbService = new Mock<IDynamoDbService>();
        _logger = new Mock<ILogger<GetStatsOperation>>();
        _sut = new GetStatsOperation(_dynamoDbService.Object, _logger.Object);
    }

    // --- Success path ---

    [TestMethod]
    public async Task ExecuteAsync_WhenBothCountersPresent_ReturnsMappedVisitsAndSubmissions()
    {
        var ct = CancellationToken.None;
        SetupCounters(new Dictionary<string, long> { ["visits"] = 42L, ["submissions"] = 7L });

        var result = await _sut.ExecuteAsync(ct);

        Assert.AreEqual(42, result.Visits);
        Assert.AreEqual(7, result.Submissions);
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenVisitsKeyMissing_ReturnsZeroVisits()
    {
        var ct = CancellationToken.None;
        SetupCounters(new Dictionary<string, long> { ["submissions"] = 5L });

        var result = await _sut.ExecuteAsync(ct);

        Assert.AreEqual(0, result.Visits);
        Assert.AreEqual(5, result.Submissions);
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenSubmissionsKeyMissing_ReturnsZeroSubmissions()
    {
        var ct = CancellationToken.None;
        SetupCounters(new Dictionary<string, long> { ["visits"] = 10L });

        var result = await _sut.ExecuteAsync(ct);

        Assert.AreEqual(10, result.Visits);
        Assert.AreEqual(0, result.Submissions);
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenDictionaryIsEmpty_ReturnsBothZeros()
    {
        var ct = CancellationToken.None;
        SetupCounters(new Dictionary<string, long>());

        var result = await _sut.ExecuteAsync(ct);

        Assert.AreEqual(0, result.Visits);
        Assert.AreEqual(0, result.Submissions);
    }

    [TestMethod]
    public async Task ExecuteAsync_CallsIncrementAndGetWithCorrectArgs()
    {
        var ct = CancellationToken.None;
        SetupCounters(new Dictionary<string, long>());

        await _sut.ExecuteAsync(ct);

        _dynamoDbService.Verify(
            d => d.IncrementAndGetAsync("app_stats", "stats", "visits", ct),
            Times.Once);
    }

    // --- Helpers ---

    private void SetupCounters(Dictionary<string, long> counters)
    {
        _dynamoDbService
            .Setup(d => d.IncrementAndGetAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(counters);
    }
}
