// Generated by MSTest Unit Test Writer Skill
using InterpolationApi.Models;
using InterpolationApi.Operations.SubmitJob;
using InterpolationApi.Services;
using Microsoft.Extensions.Logging;
using Moq;

namespace InterpolationApiTest.Operations;

[TestClass]
public class SubmitJobOperationTests
{
    private Mock<IDynamoDbService> _dynamoDbService = null!;
    private Mock<ISqsService> _sqsService = null!;
    private Mock<ILogger<SubmitJobOperation>> _logger = null!;
    private SubmitJobOperation _sut = null!;

    [TestInitialize]
    public void Setup()
    {
        _dynamoDbService = new Mock<IDynamoDbService>();
        _sqsService = new Mock<ISqsService>();
        _logger = new Mock<ILogger<SubmitJobOperation>>();
        _sut = new SubmitJobOperation(_dynamoDbService.Object, _sqsService.Object, _logger.Object);
    }

    // --- Success path ---

    [TestMethod]
    public async Task ExecuteAsync_WhenSessionExists_ReturnsJobIdWithJobPrefix()
    {
        var (input, ct) = ValidInput();
        SetupSession(input);

        var result = await _sut.ExecuteAsync(input, ct);

        Assert.StartsWith("job_", result.JobId);
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenSessionExists_ReturnsQueuedStatus()
    {
        var (input, ct) = ValidInput();
        SetupSession(input);

        var result = await _sut.ExecuteAsync(input, ct);

        Assert.AreEqual("QUEUED", result.Status);
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenSessionExists_CallsGetItemWithEmailAndUploadId()
    {
        var (input, ct) = ValidInput();
        SetupSession(input);

        await _sut.ExecuteAsync(input, ct);

        _dynamoDbService.Verify(d => d.GetItemAsync(input.Email, input.UploadId, ct), Times.Once);
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenSessionExists_UpdatesItemWithJobIdAndQueuedStep()
    {
        var (input, ct) = ValidInput();
        SetupSession(input);
        Dictionary<string, string>? capturedUpdates = null;

        _dynamoDbService
            .Setup(d => d.UpdateItemAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<Dictionary<string, string>>(), ct))
            .Callback<string, string, Dictionary<string, string>, CancellationToken>((_, _, updates, _) => capturedUpdates = updates)
            .Returns(Task.CompletedTask);

        var result = await _sut.ExecuteAsync(input, ct);

        _dynamoDbService.Verify(d => d.UpdateItemAsync(input.Email, input.UploadId, It.IsAny<Dictionary<string, string>>(), ct), Times.Once);
        Assert.IsNotNull(capturedUpdates);
        Assert.AreEqual(result.JobId, capturedUpdates["queueId"]);
        Assert.AreEqual("Queued", capturedUpdates["step"]);
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenSessionExists_SendsSqsMessageWithCorrectFields()
    {
        var (input, ct) = ValidInput();
        SetupSession(input, startFrameKey: "uploads/start.jpg", endFrameKey: "uploads/end.png");
        SqsJobMessage? capturedMessage = null;

        _sqsService
            .Setup(s => s.SendMessageAsync(It.IsAny<SqsJobMessage>(), ct))
            .Callback<SqsJobMessage, CancellationToken>((msg, _) => capturedMessage = msg)
            .Returns(Task.CompletedTask);

        var result = await _sut.ExecuteAsync(input, ct);

        Assert.IsNotNull(capturedMessage);
        Assert.AreEqual(result.JobId, capturedMessage.JobId);
        Assert.AreEqual(input.Email, capturedMessage.Email);
        Assert.AreEqual(input.UploadId, capturedMessage.UploadId);
        Assert.AreEqual("uploads/start.jpg", capturedMessage.StartFrameKey);
        Assert.AreEqual("uploads/end.png", capturedMessage.EndFrameKey);
        Assert.IsFalse(string.IsNullOrEmpty(capturedMessage.CreatedAt));
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenSessionExists_IncrementsSubmissionsCounter()
    {
        var (input, ct) = ValidInput();
        SetupSession(input);

        await _sut.ExecuteAsync(input, ct);

        _dynamoDbService.Verify(d => d.IncrementCounterAsync("app_stats", "stats", "submissions", ct), Times.Once);
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenCounterIncrementThrows_StillReturnsResult()
    {
        var (input, ct) = ValidInput();
        SetupSession(input);

        _dynamoDbService
            .Setup(d => d.IncrementCounterAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<string>(), ct))
            .ThrowsAsync(new Exception("DynamoDB unavailable"));

        var result = await _sut.ExecuteAsync(input, ct);

        Assert.AreEqual("QUEUED", result.Status);
    }

    // --- Session not found ---

    [TestMethod]
    public async Task ExecuteAsync_WhenSessionNotFound_ThrowsInvalidOperationException()
    {
        var (input, ct) = ValidInput();
        _dynamoDbService.Setup(d => d.GetItemAsync(input.Email, input.UploadId, ct)).ReturnsAsync((Dictionary<string, string>?)null);

        await Assert.ThrowsExactlyAsync<InvalidOperationException>(async () =>
            await _sut.ExecuteAsync(input, ct));
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenSessionNotFound_DoesNotCallUpdateItemOrSendMessage()
    {
        var (input, ct) = ValidInput();
        _dynamoDbService.Setup(d => d.GetItemAsync(input.Email, input.UploadId, ct)).ReturnsAsync((Dictionary<string, string>?)null);

        try { await _sut.ExecuteAsync(input, ct); } catch (InvalidOperationException) { }

        _dynamoDbService.Verify(d => d.UpdateItemAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<Dictionary<string, string>>(), ct), Times.Never);
        _sqsService.Verify(s => s.SendMessageAsync(It.IsAny<SqsJobMessage>(), ct), Times.Never);
    }

    // --- Validation failures ---

    [TestMethod]
    public async Task ExecuteAsync_WhenEmailIsEmpty_ThrowsArgumentException()
    {
        var (input, ct) = ValidInput();
        input.Email = "";

        await Assert.ThrowsExactlyAsync<ArgumentException>(async () =>
            await _sut.ExecuteAsync(input, ct));
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenEmailIsWhitespace_ThrowsArgumentException()
    {
        var (input, ct) = ValidInput();
        input.Email = "   ";

        await Assert.ThrowsExactlyAsync<ArgumentException>(async () =>
            await _sut.ExecuteAsync(input, ct));
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenUploadIdIsEmpty_ThrowsArgumentException()
    {
        var (input, ct) = ValidInput();
        input.UploadId = "";

        await Assert.ThrowsExactlyAsync<ArgumentException>(async () =>
            await _sut.ExecuteAsync(input, ct));
    }

    [TestMethod]
    public async Task ExecuteAsync_WhenUploadIdIsWhitespace_ThrowsArgumentException()
    {
        var (input, ct) = ValidInput();
        input.UploadId = "   ";

        await Assert.ThrowsExactlyAsync<ArgumentException>(async () =>
            await _sut.ExecuteAsync(input, ct));
    }

    // --- Helpers ---

    private static (SubmitJobInput input, CancellationToken ct) ValidInput() =>
    (
        new SubmitJobInput
        {
            Email    = "test@example.com",
            UploadId = "upl_abc123"
        },
        CancellationToken.None
    );

    private void SetupSession(
        SubmitJobInput input,
        string startFrameKey = "uploads/start.jpg",
        string endFrameKey   = "uploads/end.png")
    {
        _dynamoDbService
            .Setup(d => d.GetItemAsync(input.Email, input.UploadId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(new Dictionary<string, string>
            {
                ["startFrameKey"] = startFrameKey,
                ["endFrameKey"]   = endFrameKey
            });
    }
}
